using System;
using System.Collections.Generic;
using System.Linq;

namespace Ikiru.Parsnips.Api.Controllers.Sectors
{
    public static class SectorsLookup
    {
        public static IEnumerable<Sector> GetSectorsContainSearch(string search) 
            => s_Sectors.Where(c => c.Name.Contains(search, StringComparison.OrdinalIgnoreCase));

        public static Sector GetSectorById(string sectorId) => s_Sectors.SingleOrDefault(s => s.Id == sectorId);

        private static readonly List<Sector> s_Sectors = new List<Sector>
                                                     {
                                                         new Sector("I1269", "I12691", "3D Printing"),
                                                         new Sector("I103", "I1031", "Accessories"),
                                                         new Sector("I120", "I1202", "Accounting"),
                                                         new Sector("I119D2", "I119D21", "Actuarial Services"),
                                                         new Sector("I167", "I1671", "Advertising"),
                                                         new Sector("I113", "I1131", "Advertising Agencies"),
                                                         new Sector("I1561", "I15611", "Advisory"),
                                                         new Sector("I121", "I1211", "Aerospace"),
                                                         new Sector(null, "I121", "Aerospace and Defence"),
                                                         new Sector("I1223", "I12231", "Aftermarket"),
                                                         new Sector("I1621", "I16213", "Agencies and Other Public Bodies eg Advisory Committees or Arts Council"),
                                                         new Sector("I1291", "I12915", "Agricultural and Forestry Machinery"),
                                                         new Sector("I117", "I1171", "Agricultural Wholesalers"),
                                                         new Sector("I106", "I1061", "Agriculture"),
                                                         new Sector("I1211", "I12111", "Air and spacecraft and related machinery"),
                                                         new Sector("I133", "I1331", "Air Transportation"),
                                                         new Sector("I1212", "I12121", "Aircraft Manufacture"),
                                                         new Sector("I160", "I1603", "Airforce"),
                                                         new Sector("I116", "I1161", "Airlines"),
                                                         new Sector("I155", "I1559", "Alternative Dispute Resolution"),
                                                         new Sector(null, "I149", "Alternative Energy"),
                                                         new Sector("I159", "I1591", "Ambulance"),
                                                         new Sector("I1062", "I10621", "Animal Feed Manufacturing"),
                                                         new Sector(null, "I137", "Animal Health"),
                                                         new Sector("I137", "I1371", "Animal Pharmaceuticals"),
                                                         new Sector("I115", "I1151", "Antiques"),
                                                         new Sector("I107", "I1071", "Apparel Retailers"),
                                                         new Sector("I171", "I1711", "Applications - Consumer mobile"),
                                                         new Sector("I151", "I1511", "Architects"),
                                                         new Sector("I160", "I1601", "Army"),
                                                         new Sector("I171", "I1712", "Artificial Intelligence"),
                                                         new Sector(null, "I101", "Arts and Creative Entertainment"),
                                                         new Sector("I1624", "I16242", "Arts, Social Sciences and Humanities Research"),
                                                         new Sector("I119D", "I119D1", "Asset Management"),
                                                         new Sector("I107", "I1073", "Auction Houses"),
                                                         new Sector("I120", "I1201", "Audit"),
                                                         new Sector("I171", "I1713", "Augmented and Virtual Reality"),
                                                         new Sector(null, "I163", "Automation"),
                                                         new Sector("I126", "I1269", "Automation Technology"),
                                                         new Sector("I107", "I1072", "Automobile and Motorcycle Retailing"),
                                                         new Sector("I109", "I1091", "Automobiles"),
                                                         new Sector("I117", "I1172", "Automobiles and Motorcycles"),
                                                         new Sector(null, "I122", "Automotive"),
                                                         new Sector("I109", "I1095", "Automotive maintenance and repair"),
                                                         new Sector("I122", "I1223", "Automotive Parts"),
                                                         new Sector("I1091", "I10911", "Automotive parts and accessories"),
                                                         new Sector(null, "I109", "Automotive Retailers"),
                                                         new Sector("I121", "I1212", "Aviation"),
                                                         new Sector(null, "I119", "Banking and Finance"),
                                                         new Sector("I155", "I1552", "Barristers"),
                                                         new Sector("I104", "I1041", "Beauty"),
                                                         new Sector(null, "I102", "Beverages"),
                                                         new Sector("I1291", "I12918", "Bicycles"),
                                                         new Sector("I1715", "I17151", "Big Data"),
                                                         new Sector("I144", "I1442", "Biotech"),
                                                         new Sector("I168", "I1683", "Blockchain/Bitcoin"),
                                                         new Sector("I1134", "I11341", "Book Publishing"),
                                                         new Sector("I1346", "I13461", "Books and Newspaper printing"),
                                                         new Sector("I102", "I1021", "Brewers"),
                                                         new Sector(null, "I164", "Broadcasting"),
                                                         new Sector("I125", "I1252", "Building Materials and Fixtures"),
                                                         new Sector(null, "I151", "Built Environment"),
                                                         new Sector("I1251", "I12511", "Built Environment Materials"),
                                                         new Sector("I1672", "I16721", "Business Information resources and databases"),
                                                         new Sector(null, "I150", "Business Process Outsourcing (BPO)"),
                                                         new Sector("I167", "I1672", "Business Publishing"),
                                                         new Sector("I1541", "I15411", "Business Training and Employment"),
                                                         new Sector("I166", "I1661", "Cable"),
                                                         new Sector("I170", "I1701", "Call Centres"),
                                                         new Sector("I116", "I1162", "Camping and Outdoor Equipment"),
                                                         new Sector(null, "I123", "Capital Equipment"),
                                                         new Sector("I119", "I119G", "Capital Market"),
                                                         new Sector("I109", "I1093", "Caravans and Motorhomes"),
                                                         new Sector("I1681", "I16811", "Card payment systems"),
                                                         new Sector("I140", "I1401", "Care Homes"),
                                                         new Sector("I1335", "I13351", "Cargo Services"),
                                                         new Sector("I122", "I1222", "Cars and Motorcycles"),
                                                         new Sector("I119E", "I119E1", "Cash Management"),
                                                         new Sector("I152", "I1521", "Catering Management"),
                                                         new Sector("I162", "I1621", "Central Government"),
                                                         new Sector("I1561", "I15612", "Change Management"),
                                                         new Sector("I161", "I1611", "Charities"),
                                                         new Sector("I117", "I1173", "Chemical and Chemical products"),
                                                         new Sector(null, "I124", "Chemicals"),
                                                         new Sector("I103", "I1032", "Childrenswear"),
                                                         new Sector("I116", "I1163", "Cinema and Night Clubs"),
                                                         new Sector("I155", "I1551", "City Law Firms"),
                                                         new Sector("I161", "I1618", "Civic & Social Organisation"),
                                                         new Sector("I125", "I1253", "Civil Engineering"),
                                                         new Sector("I1621", "I16216", "Civil Service"),
                                                         new Sector("I1522", "I15221", "Cleaning and Maintenance Services"),
                                                         new Sector(null, "I103", "Clothing & Accessories"),
                                                         new Sector("I117", "I1174", "Clothing and Accessories"),
                                                         new Sector("I107", "I1074", "Clothing and Accessories Retailers"),
                                                         new Sector("I165", "I1651", "Cloud Computing"),
                                                         new Sector("I1483", "I14833", "CO2 Storage"),
                                                         new Sector("I147", "I1471", "Coal Mining"),
                                                         new Sector("I1582", "I15821", "Colleges, Language Schools"),
                                                         new Sector("I1331", "I13312", "Commercial Air Transport"),
                                                         new Sector("I125", "I1254", "Commercial Construction"),
                                                         new Sector("I146", "I1461", "Commercial Fishing"),
                                                         new Sector("I173", "I1731", "Commercial Real Estate"),
                                                         new Sector("I1334", "I13342", "Commercial Road Transport"),
                                                         new Sector("I1332", "I13322", "Commercial Shipping"),
                                                         new Sector("I109", "I1092", "Commercial Vehicles"),
                                                         new Sector("I122", "I1221", "Commercial Vehicles and Trucks"),
                                                         new Sector("I1172", "I11721", "Commercial Vehicles, Caravans and Trailers"),
                                                         new Sector("I124", "I1241", "Commodity Chemicals (e.g petrochemicals, polymers, basic inorganics)"),
                                                         new Sector(null, "I166", "Communications Technology"),
                                                         new Sector("I1541", "I15412", "Compensation and Benefits Consultants"),
                                                         new Sector("I119B", "I119B1", "Compliance"),
                                                         new Sector("I1264", "I12641", "Computer Games"),
                                                         new Sector("I125", "I1251", "Construction"),
                                                         new Sector(null, "I125", "Construction and Materials"),
                                                         new Sector("I1253", "I12531", "Construction of Roads and Railways, bridges and tunnels"),
                                                         new Sector("I1253", "I12532", "Construction of Utility projects, including for power and water"),
                                                         new Sector(null, "I104", "Consumer Care Products"),
                                                         new Sector("I124", "I1242", "Consumer Chemicals (e.g, detergents, soaps, toiletries)"),
                                                         new Sector("I112", "I1121", "Consumer Electronics"),
                                                         new Sector("I119", "I119A", "Consumer Finance"),
                                                         new Sector(null, "I138", "Consumer Healthcare"),
                                                         new Sector("I104", "I1042", "Consumer Healthcare Products"),
                                                         new Sector("I110", "I1101", "Consumer Healthcare Retailers"),
                                                         new Sector("I119A1", "I119A13", "Consumer Leasing"),
                                                         new Sector("I119A1", "I119A12", "Consumer Lending incl Credit Cards"),
                                                         new Sector("I119A1", "I119A11", "Consumer Mortgages"),
                                                         new Sector(null, "I105", "Consumer Produced Products"),
                                                         new Sector("I117", "I1175", "Consumer Products"),
                                                         new Sector("I167", "I1673", "Consumer Publishing"),
                                                         new Sector("", "I12811", "Containers and Packaging"),
                                                         new Sector("I119", "I1192", "Corporate Finance"),
                                                         new Sector("I116B", "I116B1", "Cricket, Football, Cricket, Athletics etc"),
                                                         new Sector("I155", "I1554", "Crime Management"),
                                                         new Sector("I143", "I1431", "Critical Care"),
                                                         new Sector("I1684", "I16841", "Crowdfunding"),
                                                         new Sector("I116", "I1164", "Cruises"),
                                                         new Sector("I171", "I1714", "Cyber Security"),
                                                         new Sector("I171", "I1715", "Data Management"),
                                                         new Sector(null, "I165", "Data Management and Storage"),
                                                         new Sector("I171", "I1716", "Data Security"),
                                                         new Sector("I119B", "I119B2", "Debt Structuring"),
                                                         new Sector("I119", "I1193", "Debt Trading"),
                                                         new Sector("I121", "I1213", "Defence"),
                                                         new Sector("I1141", "I11411", "Delivery Services"),
                                                         new Sector("I134", "I1345", "Dental Equipment"),
                                                         new Sector("I138", "I1381", "Dentistry"),
                                                         new Sector("I119", "I1194", "Derivatives"),
                                                         new Sector("I162", "I1622", "Devolved Administrations"),
                                                         new Sector("I1421", "I14211", "Diagnostics"),
                                                         new Sector("I1473", "I14732", "Diamond and Gemstone Mining"),
                                                         new Sector("I168", "I1684", "Digital Lending"),
                                                         new Sector("I176", "I1761", "Digital Marketing"),
                                                         new Sector("I167", "I1674", "Digital Music"),
                                                         new Sector(null, "I167", "Digital Publishing"),
                                                         new Sector("I1642", "I16421", "Digital Radio"),
                                                         new Sector("I1641", "I16411", "Digital Television"),
                                                         new Sector("I102", "I1022", "Distillers"),
                                                         new Sector("I1267", "I12672", "Domestic Electrical Equipment"),
                                                         new Sector("I148", "I1482", "Downstream Activities"),
                                                         new Sector("I163", "I1632", "Driverless Cars"),
                                                         new Sector("I163", "I1631", "Drones"),
                                                         new Sector("I144", "I1443", "Drug Manufacturing"),
                                                         new Sector("I1101", "I11011", "Drug Retailers"),
                                                         new Sector("I139", "I1392", "E Health Services"),
                                                         new Sector(null, "I108", "E-Commerce"),
                                                         new Sector(null, "I158", "Education"),
                                                         new Sector("I1622", "I16221", "eg Scotland, Wales and Northern Ireland, Individual US State Administration"),
                                                         new Sector("I117", "I1176", "Electrical and Electronic Equipment"),
                                                         new Sector("I1267", "I12671", "Electrical Motors, batteries, generators and lighting"),
                                                         new Sector(null, "I126", "Electronic, Engineering and Electrical Equipment"),
                                                         new Sector(null, "I159", "Emergency Response"),
                                                         new Sector("I1532", "I15321", "Employment Agencies"),
                                                         new Sector(null, "I153", "Employment Services"),
                                                         new Sector("I126", "I126A", "Engineering Design"),
                                                         new Sector("I1291", "I12911", "Engines and Turbines"),
                                                         new Sector("I1718", "I17181", "Enterprise resource planning (ERP), customer relationship management (CRM)"),
                                                         new Sector("I113", "I1133", "Entertainment Media"),
                                                         new Sector("I1561", "I15613", "Environmental Consulting"),
                                                         new Sector("I119", "I1195", "Equities"),
                                                         new Sector("I108", "I1081", "Etailing"),
                                                         new Sector("I1167", "I11671", "Events Management"),
                                                         new Sector("I153", "I1531", "Executive Search"),
                                                         new Sector("I148", "I1481", "Exploration and Production"),
                                                         new Sector(null, "I152", "Facilities Management"),
                                                         new Sector("I143", "I1432", "Family Medicine (GPs)"),
                                                         new Sector("I1071", "I10711", "Fashion and Accessories Retailers"),
                                                         new Sector("I1081", "I10811", "Fashion and apparel Etail"),
                                                         new Sector("I1622", "I16222", "Federal Executives"),
                                                         new Sector("I1133", "I11331", "Film and Video"),
                                                         new Sector("I120", "I1203", "Financial Advisory"),
                                                         new Sector(null, "I120", "Financial Management"),
                                                         new Sector("I120", "I1204", "Financial Planning and Analysis"),
                                                         new Sector("I119", "I119B", "Financial Risk Management"),
                                                         new Sector(null, "I168", "FinTech"),
                                                         new Sector("I159", "I1592", "Fire and Rescue"),
                                                         new Sector("I146", "I1462", "Fish Farming"),
                                                         new Sector(null, "I146", "Fishing and Aquaculture"),
                                                         new Sector("I119", "I1196", "Fixed Income"),
                                                         new Sector("I166", "I1662", "Fixed line telecommunications"),
                                                         new Sector("I1291", "I12912", "Fluid Power Equipment and Pumps"),
                                                         new Sector(null, "I110", "Food & Drug Retailers"),
                                                         new Sector("I117", "I1177", "Food and Beverages"),
                                                         new Sector("I106", "I1062", "Food Manufacturing"),
                                                         new Sector("I106", "I1063", "Food Processing"),
                                                         new Sector(null, "I106", "Food Producers"),
                                                         new Sector("I110", "I1102", "Food Retailers"),
                                                         new Sector("I103", "I1033", "Footwear"),
                                                         new Sector("I1422", "I14223", "Forensic Science"),
                                                         new Sector(null, "I128", "Forest Products"),
                                                         new Sector(null, "I145", "Forestry"),
                                                         new Sector("I119", "I1197", "Forex"),
                                                         new Sector("I119D1", "I119D12", "Fund Adminstration"),
                                                         new Sector("I111", "I1114", "Furniture and Household Furnishing Retailing"),
                                                         new Sector("I1282", "I12821", "Furniture Production"),
                                                         new Sector("I158", "I1582", "Further Education"),
                                                         new Sector("I119", "I1198", "Futures and Options"),
                                                         new Sector("I116", "I1165", "Gambling"),
                                                         new Sector("I105", "I1051", "Games and Toys (excluding electronics)"),
                                                         new Sector("I134", "I1344", "Games and Toys (not electronic)"),
                                                         new Sector("I112", "I1124", "Games and Toys Retailing (not electronic)"),
                                                         new Sector("I1112", "I11121", "Garden Centres"),
                                                         new Sector("I1081", "I10812", "General Etail"),
                                                         new Sector("I119C", "I119C1", "General Insurance"),
                                                         new Sector(null, "I107", "General Retailers"),
                                                         new Sector("I127", "I1271", "Generation, Transmission and Production"),
                                                         new Sector("I124", "I1243", "Glass"),
                                                         new Sector("I1473", "I14731", "Gold and Platinum Mining"),
                                                         new Sector("I166", "I1663", "GPS"),
                                                         new Sector("I1612", "I16122", "Grant Making Trusts"),
                                                         new Sector("I161", "I1612", "Grants and Funding"),
                                                         new Sector("I1169", "I11691", "Hairdressing, Beauty Salons"),
                                                         new Sector("I113", "I1134", "Hard Copy Publishing"),
                                                         new Sector("I169", "I1691", "Hardware"),
                                                         new Sector("I117", "I1178", "Hardware, Plumbing and Heating Equipment"),
                                                         new Sector(null, "I140", "Health Care Providers"),
                                                         new Sector("I116", "I1166", "Health Clubs and Gyms"),
                                                         new Sector("I1392", "I13921", "Health Data Management"),
                                                         new Sector("I140", "I1402", "Health Insurance"),
                                                         new Sector(null, "I139", "Healthcare Equipment and Services"),
                                                         new Sector("I119D1", "I119D11", "Hedge Funds"),
                                                         new Sector("I101", "I1011", "Heritage Sites"),
                                                         new Sector("I1621", "I16214", "High Profile Groups eg Border Force, Passport Office"),
                                                         new Sector("I158", "I1583", "Higher Education"),
                                                         new Sector("I117", "I1179", "Home and Garden Products"),
                                                         new Sector(null, "I111", "Home and Garden Retailers"),
                                                         new Sector("I111", "I1111", "Home Improvement Retailers"),
                                                         new Sector("I116", "I1167", "Hospitality"),
                                                         new Sector("I116", "I1168", "Hotels"),
                                                         new Sector("I104", "I1043", "Household Care Products"),
                                                         new Sector(null, "I154", "Human Capital"),
                                                         new Sector("I1541", "I15413", "Human Resources Consulting"),
                                                         new Sector("I154", "I1541", "Human Resources Management"),
                                                         new Sector("I1581", "I15812", "Independent Schools"),
                                                         new Sector("I1265", "I12652", "Industrial Process Control Equipment"),
                                                         new Sector("I1176", "I11761", "Information and Communication Equipment"),
                                                         new Sector("I119", "I119C", "Insurance"),
                                                         new Sector("I119C1", "I119C12", "Insurance Broking"),
                                                         new Sector("I119C1", "I119C11", "Insurance Underwriting"),
                                                         new Sector("I172", "I1721", "Intellectual Property"),
                                                         new Sector("I1681", "I16812", "Interbank payment systems eg BACS or CHAPS"),
                                                         new Sector("I171", "I1717", "Internet of Things"),
                                                         new Sector("I166", "I1664", "Internet Service Providers"),
                                                         new Sector("I119", "I1191", "Investment Banking"),
                                                         new Sector("I119", "I119D", "Investment Management"),
                                                         new Sector("I1472", "I14721", "Iron Ore Extraction"),
                                                         new Sector("I168", "I1685", "Istech (Insurance Technology)"),
                                                         new Sector("I150", "I1501", "IT Outsourcing"),
                                                         new Sector("I134", "I1343", "Jewellery"),
                                                         new Sector("I1055", "I10551", "Jewellery and Watches"),
                                                         new Sector("I155", "I1556", "Judiciary"),
                                                         new Sector("I155", "I1557", "Law Enforcement"),
                                                         new Sector(null, "I155", "Legal"),
                                                         new Sector("I155", "I1558", "Legislative Office"),
                                                         new Sector(null, "I112", "Leisure Goods Retailing"),
                                                         new Sector("I105", "I1052", "Leisure Products"),
                                                         new Sector("I117", "I117A", "Leisure Products Wholesale"),
                                                         new Sector("I119B", "I119B3", "Leveraged Finance"),
                                                         new Sector("I101", "I1012", "Libraries (Arts and Creative Entertainment)"),
                                                         new Sector("I1592", "I15921", "Life Boat and Mountain Rescue"),
                                                         new Sector("I119C1", "I119C14", "Life Insurance"),
                                                         new Sector("I1291", "I12914", "Lifting and handling Equipment"),
                                                         new Sector("I119B", "I119B4", "Loan Syndication"),
                                                         new Sector("I162", "I1623", "Local Government"),
                                                         new Sector("I1623", "I16231", "Local Government Management"),
                                                         new Sector("I145", "I1451", "Logging and wood production"),
                                                         new Sector("I157", "I1571", "Logistics"),
                                                         new Sector("I133", "I1335", "Logistics and Distribution"),
                                                         new Sector("I1612", "I16121", "Lotteries"),
                                                         new Sector("I1483", "I14832", "LPG"),
                                                         new Sector("I1153", "I11531", "LPG and Fuel Retailers"),
                                                         new Sector("I105", "I1055", "Luxury Goods"),
                                                         new Sector(null, "I129", "Machinery and Equipment"),
                                                         new Sector("I117", "I117B", "Machinery, Equipment and Supplies"),
                                                         new Sector("I114", "I1141", "Mail Services"),
                                                         new Sector(null, "I156", "Management Consulting"),
                                                         new Sector("I127", "I1272", "Manufacture and Distribution of Gas via Mains"),
                                                         new Sector("I132", "I1321", "Manufacture of Apparel"),
                                                         new Sector("I1252", "I12521", "Manufacture of building materials including concrete, bricks,"),
                                                         new Sector("I131", "I1311", "Manufacture of Commercial Ships and Floating Structures"),
                                                         new Sector("I126", "I1263", "Manufacture of Communication Equipment"),
                                                         new Sector("I126", "I1262", "Manufacture of Computers and Peripheral Equipment"),
                                                         new Sector("I126", "I1264", "Manufacture of Consumer Electronics"),
                                                         new Sector("I126", "I1267", "Manufacture of Electrical Equipment"),
                                                         new Sector("I126", "I1261", "Manufacture of Electronic Components and Boards"),
                                                         new Sector("I132", "I1322", "Manufacture of Footwear"),
                                                         new Sector("I126", "I1265", "Manufacture of instruments and appliances for measuring, testing and navigation"),
                                                         new Sector("I129", "I1291", "Manufacture of Machinery"),
                                                         new Sector("I126", "I1266", "Manufacture of Optical Instruments and Camera Equipment"),
                                                         new Sector("I131", "I1312", "Manufacture of Pleasure and sport Craft"),
                                                         new Sector("I130", "I1301", "Manufacture of Rail Transportation Equipment and Rolling Stock"),
                                                         new Sector("I126", "I1268", "Manufacture of Semiconductors"),
                                                         new Sector("I133", "I1332", "Marine Transportation"),
                                                         new Sector(null, "I176", "Marketing"),
                                                         new Sector("I1261", "I12611", "Mechatronics"),
                                                         new Sector("I113", "I1132", "Media Agencies"),
                                                         new Sector(null, "I113", "Media and Publishing"),
                                                         new Sector("I139", "I1391", "Medical Equipment and Supplies"),
                                                         new Sector("I1422", "I14222", "Medical Imaging"),
                                                         new Sector(null, "I143", "Medicine"),
                                                         new Sector(null, "I142", "Medtech"),
                                                         new Sector("I103", "I1034", "Menswear"),
                                                         new Sector("I1291", "I12916", "Metal Forming machinery and machine tools"),
                                                         new Sector("I147", "I1472", "Metal Mining"),
                                                         new Sector("I117", "I117C", "Metals"),
                                                         new Sector("I16231", "I162311", "Metropolitan Councils, Greater London, Counties and overseas equivalents"),
                                                         new Sector("I148", "I1483", "Midstream Activities"),
                                                         new Sector(null, "I160", "Military"),
                                                         new Sector("I1213", "I12131", "Military fighting vehicles"),
                                                         new Sector(null, "I147", "Mining and Quarrying"),
                                                         new Sector("I1475", "I14751", "Mining support activities"),
                                                         new Sector("I147", "I1475", "Mining Support Service Activities"),
                                                         new Sector("I1621", "I16211", "Ministerial Departments"),
                                                         new Sector("I110", "I1103", "Mixed Retail"),
                                                         new Sector("I168", "I1682", "Mobile and Digital Banking"),
                                                         new Sector("I1263", "I12631", "Mobile Phone and Tablet production"),
                                                         new Sector("I109", "I1094", "Motorcycles"),
                                                         new Sector("I1621", "I16217", "Museums and Arts Administration"),
                                                         new Sector("I101", "I1013", "Museums and Galleries"),
                                                         new Sector("I1133", "I11332", "Music"),
                                                         new Sector("I112", "I1125", "Music - vinyl and CDs, streaming"),
                                                         new Sector("I105", "I1053", "Musical Instruments"),
                                                         new Sector("I134", "I1341", "Musical Instruments Manufacturing"),
                                                         new Sector("I115", "I1152", "Musical Instruments Retail"),
                                                         new Sector("I1623", "I16232", "National Parks"),
                                                         new Sector("I160", "I1602", "Navy"),
                                                         new Sector("I1692", "I16921", "Network enablement, internet connectivity, firewall and security"),
                                                         new Sector(null, "I169", "Networking and IT Infrastructure"),
                                                         new Sector("I169", "I1692", "Networks"),
                                                         new Sector("I1134", "I11342", "Newspapers and Magazines"),
                                                         new Sector("I161", "I1614", "NGOs (Non Governmental Organisations)"),
                                                         new Sector("I140", "I1403", "NHS (UK only)"),
                                                         new Sector("I1472", "I14722", "Non Ferrous Metal Mining"),
                                                         new Sector("I1621", "I16212", "Non Ministerial Departments eg Crown Prosecution Service"),
                                                         new Sector("I119C1", "I119C15", "Non-Life Insurance"),
                                                         new Sector(null, "I161", "Not for Profit"),
                                                         new Sector("I1271", "I12711", "Nuclear Energy"),
                                                         new Sector("I149", "I1491", "Nuclear Power"),
                                                         new Sector("I1223", "I12232", "OEMs (Original Equipment Manufacturers)"),
                                                         new Sector("I105", "I1056", "Office Supplies"),
                                                         new Sector(null, "I170", "Office Support Activities"),
                                                         new Sector("I115", "I1153", "Oil and Gas"),
                                                         new Sector("I117", "I117D", "Oil and Gas and Fuel"),
                                                         new Sector(null, "I148", "Oil and Gas Extraction"),
                                                         new Sector("I1481", "I14811", "Oil and Gas Support Activities"),
                                                         new Sector("I1482", "I14821", "Oil Refining"),
                                                         new Sector("I1711", "I17111", "On demand applications eg Uber"),
                                                         new Sector("I138", "I1383", "Ophthalmology"),
                                                         new Sector("I138", "I1382", "OTC Medicines"),
                                                         new Sector(null, "I134", "Other Manufacturing"),
                                                         new Sector(null, "I118", "Other Professional Specialist Activities"),
                                                         new Sector("I1291", "I12913", "Ovens and Furnaces"),
                                                         new Sector("I161", "I1615", "Overseas Development"),
                                                         new Sector("I128", "I1281", "Paper Production"),
                                                         new Sector("I1331", "I13311", "Passenger Air Transport"),
                                                         new Sector("I1332", "I13321", "Passenger Ferries, Cruise Shipping"),
                                                         new Sector("I1334", "I13341", "Passenger Rail Transport"),
                                                         new Sector("I1333", "I13331", "Passenger Road Transport"),
                                                         new Sector("I155", "I1555", "Patent and Copyright Experts"),
                                                         new Sector("I1422", "I14221", "Pathology"),
                                                         new Sector("I168", "I1681", "Payment Systems"),
                                                         new Sector("I1681", "I16813", "Payment Systems Infrastructure eg. Vocalink"),
                                                         new Sector("I119D", "I119D2", "Pension Fund Management"),
                                                         new Sector("I116", "I1169", "Personal Service Activities"),
                                                         new Sector("I111", "I1112", "Petcare Retailers"),
                                                         new Sector(null, "I144", "Pharmaceuticals and Biotech"),
                                                         new Sector("I161", "I1616", "Philanthropic Organisations"),
                                                         new Sector("I118", "I1181", "Photographic Activities"),
                                                         new Sector("I1483", "I14831", "Pipelines and Transmission"),
                                                         new Sector("I124", "I1244", "Plastics"),
                                                         new Sector("I1554", "I15541", "Police"),
                                                         new Sector(null, "I114", "Postal and Courier Services"),
                                                         new Sector(null, "I127", "Power"),
                                                         new Sector("I147", "I1473", "Precious Metal Mining"),
                                                         new Sector("I119E", "I119E2", "Prime Brokerage"),
                                                         new Sector("I134", "I1346", "Printing"),
                                                         new Sector("I119", "I119F", "Private Equity"),
                                                         new Sector("I157", "I1572", "Procurement"),
                                                         new Sector(null, "I157", "Procurement and Supply Chain"),
                                                         new Sector("I171", "I1718", "Productivity Applications"),
                                                         new Sector("I161", "I1613", "Professional and Membership Organisations (eg Trade Unions, Professional Organisations)"),
                                                         new Sector("I152", "I1522", "Property Management"),
                                                         new Sector("I138", "I1384", "Psychiatry and Counselling"),
                                                         new Sector("I1531", "I15311", "Psychometric Assessment Services"),
                                                         new Sector("I1621", "I16215", "Public Corporations eg BBC or Historic Royal Palaces"),
                                                         new Sector("I1623", "I16233", "Public Service Libraries"),
                                                         new Sector(null, "I162", "Public Services"),
                                                         new Sector("I147", "I1474", "Quarrying"),
                                                         new Sector("I164", "I1642", "Radio"),
                                                         new Sector(null, "I130", "Rail"),
                                                         new Sector("I133", "I1334", "Rail Transportation"),
                                                         new Sector(null, "I173", "Real Estate"),
                                                         new Sector("I119D1", "I119D13", "Real Estate Investment"),
                                                         new Sector("I112", "I1122", "Recreational Products"),
                                                         new Sector("I1541", "I15414", "Recruitment and Executive Search"),
                                                         new Sector("I153", "I1532", "Recruitment Services"),
                                                         new Sector("I119C1", "I119C13", "Reinsurance"),
                                                         new Sector("I161", "I1619", "Religious Institutions"),
                                                         new Sector("I127", "I1274", "Renewable Energy"),
                                                         new Sector("I149", "I1492", "Renewables"),
                                                         new Sector("I123", "I1231", "Renting and Leasing of Capital Equipment"),
                                                         new Sector("I1231", "I12311", "Renting and leasing of vehicles, agricultural equipment etc"),
                                                         new Sector("I142", "I1421", "Research"),
                                                         new Sector("I119", "I1199", "Research and Analysis"),
                                                         new Sector("I144", "I1441", "Research and Drug Development"),
                                                         new Sector("I125", "I1255", "Residential Construction"),
                                                         new Sector("I173", "I1732", "Residential Real Estate"),
                                                         new Sector("I116", "I116A", "Restaurants and Bars"),
                                                         new Sector("I119A", "I119A1", "Retail Banking"),
                                                         new Sector("I1311", "I13111", "Rig construction"),
                                                         new Sector("I133", "I1333", "Road Transportation"),
                                                         new Sector("I163", "I1633", "Robotics"),
                                                         new Sector("I166", "I1665", "Satellite Communications"),
                                                         new Sector("I119A1", "I119A14", "Savings"),
                                                         new Sector("I158", "I1581", "Schools"),
                                                         new Sector("I162", "I1624", "Scientific and Technical Agencies"),
                                                         new Sector("I1624", "I16241", "Scientific Research"),
                                                         new Sector("I1291", "I12919", "Security Devices"),
                                                         new Sector("I1554", "I15542", "Security Services"),
                                                         new Sector("I1691", "I16911", "Servers, computers, data centers, switches, hubs and routers, etc."),
                                                         new Sector("I152", "I1523", "Shared Services Centres"),
                                                         new Sector(null, "I131", "Ship Building"),
                                                         new Sector("I1667", "I16671", "Smart Cities"),
                                                         new Sector("I169", "I1693", "Smart Grid"),
                                                         new Sector("I171", "I1719", "Social Media"),
                                                         new Sector("I1719", "I17191", "Social Networking and blogging"),
                                                         new Sector("I102", "I1024", "Soft Drinks"),
                                                         new Sector(null, "I171", "Software and Computer Services"),
                                                         new Sector("I1492", "I14921", "Solar Power, Wind Power, Hydropower, Biofuels"),
                                                         new Sector("I155", "I1553", "Solicitors"),
                                                         new Sector("I126A", "I126A1", "Space Planning"),
                                                         new Sector("I1291", "I12917", "Special purpose machinery - eg for Oil and Gas extraction"),
                                                         new Sector("I118", "I1182", "Specialised Design Activities"),
                                                         new Sector("I170", "I1702", "Specialised Office Support Activities"),
                                                         new Sector("I1561", "I15615", "Specialist Sector Consulting- e.g Engineering or Security"),
                                                         new Sector("I124", "I1245", "Speciality Chemicals (e.g crop protection, paints and colourants)"),
                                                         new Sector(null, "I115", "Speciality Retailers"),
                                                         new Sector("I116", "I116B", "Sport Clubs and Venues"),
                                                         new Sector("I105", "I1054", "Sports Goods"),
                                                         new Sector("I134", "I1342", "Sports Goods Manufacturing"),
                                                         new Sector("I112", "I1123", "Sports Goods Retailing"),
                                                         new Sector("I143", "I1433", "Sports Science and Physiotherapy"),
                                                         new Sector("I1581", "I15811", "State Schools"),
                                                         new Sector("I127", "I1273", "Steam and Air Conditioning and Supply"),
                                                         new Sector("I156", "I1561", "Strategy Consulting"),
                                                         new Sector("I1103", "I11031", "Supermarkets"),
                                                         new Sector("I157", "I1573", "Supply Chain"),
                                                         new Sector("I151", "I1512", "Surveyors"),
                                                         new Sector("I1561", "I15614", "Sustainability Consulting"),
                                                         new Sector("I120", "I1205", "Tax"),
                                                         new Sector("I1561", "I15616", "Technology Consulting"),
                                                         new Sector(null, "I172", "Technology Research and Development"),
                                                         new Sector("I164", "I1641", "Television"),
                                                         new Sector("I1133", "I11333", "Television and Radio"),
                                                         new Sector("I142", "I1422", "Testing"),
                                                         new Sector(null, "I132", "Textiles"),
                                                         new Sector("I101", "I1014", "Theatres and Opera Venues"),
                                                         new Sector("I161", "I1617", "Think Tanks"),
                                                         new Sector("I106", "I1064", "Tobacco"),
                                                         new Sector("I151", "I1513", "Town Planning"),
                                                         new Sector("I168", "I1686", "Trading"),
                                                         new Sector("I119", "I119E", "Transaction Banking"),
                                                         new Sector("I118", "I1183", "Translation and Interpretation Activities"),
                                                         new Sector(null, "I133", "Transportation"),
                                                         new Sector("I157", "I1574", "Transportation Supply Chain"),
                                                         new Sector("I116", "I116C", "Travel & Tourism"),
                                                         new Sector(null, "I116", "Travel and Leisure"),
                                                         new Sector("I119D", "I119D3", "Treasury"),
                                                         new Sector("I1333", "I13332", "Trucking"),
                                                         new Sector("I1583", "I15831", "Universities"),
                                                         new Sector(null, "I136", "Utilities"),
                                                         new Sector("I119F", "I119F1", "Venture Capital"),
                                                         new Sector("I137", "I1372", "Veterinary Practices"),
                                                         new Sector("I158", "I1584", "Vocational Education"),
                                                         new Sector("I166", "I1666", "VOIP"),
                                                         new Sector("I1335", "I13352", "Warehousing"),
                                                         new Sector("I13611", "I136112", "Waste and Disposal Services"),
                                                         new Sector("I13611", "I136111", "Waste Management"),
                                                         new Sector("I117", "I117E", "Waste Products and Scrap"),
                                                         new Sector("I1265", "I12651", "Watches, Navigational Equipment"),
                                                         new Sector("I136", "I1361", "Water"),
                                                         new Sector("I1361", "I13611", "Water Supply"),
                                                         new Sector("I171", "I171A", "Web Hosting"),
                                                         new Sector("I111", "I1113", "White Good Retailers"),
                                                         new Sector(null, "I117", "Wholesaling"),
                                                         new Sector("I1274", "I12741", "Wind, Solar and Tidal Projects"),
                                                         new Sector("I102", "I1023", "Wine Producers"),
                                                         new Sector("I166", "I1667", "Wireless"),
                                                         new Sector("I103", "I1035", "Womenswear"),
                                                         new Sector("I115", "I1154", "Wood and Construction Materials"),
                                                         new Sector("I1282", "I12822", "Wood construction products"),
                                                         new Sector("I128", "I1282", "Wood Production"),
                                                         new Sector("I101", "I1015", "Zoos and Botanical Gardens")
                                                     };

        public class Sector
        {
            // ReSharper disable UnusedAutoPropertyAccessor.Global
            public string ParentId { get; }
            public string Id { get; }
            public string Name { get; }
            // ReSharper restore UnusedAutoPropertyAccessor.Global

            public Sector(string parentId, string id, string name)
            {
                ParentId = parentId;
                Id = id;
                Name = name;
            }
        }
    }
}
