name: FP_API_CI_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - story/*
  - bug/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: Release

stages:
  - stage: BuildandTest

    jobs:
      - job: Api
        displayName: "Talentis API and Functions"
        workspace:
          clean: all

        steps:
          - pwsh: |
              Write-Host "Starting CosmosDB Emulator"
              Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
              Start-CosmosDbEmulator -NoUI
            displayName: 'Start Cosmos DB Emulator'
            failOnStderr: true
            errorActionPreference: stop
            env:
              AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE : false  
          - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
            displayName: 'Prepare analysis on SonarCloud'
            inputs:
              SonarCloud: SonarCloud
              scannerMode: 'MSBuild'
              organization: 'ikiru-people'
              projectKey: 'ikiru-people_ProjectFP_API_CI'
              projectName: 'Talentis-API-CI'

          - task: PowerShell@2
            displayName: 'Start Azure Storage Emulator'
            inputs:
              targetType: 'inline'
              script: |
                npm install -g azurite
                Start-Process powershell.exe azurite 

          - task: DotNetCoreCLI@2
            displayName: Restore packages
            inputs:
              feedsToUse: 'select'
              vstsFeed: 'IkiruPeopleArtifactsFeed'
              command: restore
              projects: '**/*[Tt]ests/*.csproj'
              includeNuGetOrg: true

          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test
              projects: "**/*[Tt]ests/*.csproj"
              arguments: "--configuration $(buildConfiguration) --no-restore"

          - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
            displayName: 'Run Code Analysis'
