parameters:
- name: 'EnvName'
- name: 'AzureSub'

stages:
- stage: '${{ parameters.EnvName }}Deploy'
  displayName: '${{ parameters.EnvName }} - Deploy'

  jobs:
  # Deploy Infrastructure Job
  - template: API_DeployInfrastructure.yml
    parameters:
      EnvName: '${{ parameters.EnvName }}'
      AzureSub: '${{ parameters.AzureSub }}'

  # Deploy Search Indexes Job
  - template: API_DeploySearchIndexes.yml
    parameters:
      EnvName: '${{ parameters.EnvName }}'
      AzureSub: '${{ parameters.AzureSub }}'
      DropIfExists: '$(recreateSearchIndex)'

  # Deploy Apps Job
  - template: API_DeployApps.yml
    parameters:
      EnvName: '${{ parameters.EnvName }}'
      AzureSub: '${{ parameters.AzureSub }}'